version: '3.8'
services:
  api-my-readings:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: api-my-readings
    restart: always
    entrypoint: sh -c "yarn install && yarn start:dev"
    env_file:
      - .env.aws
    environment:
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_PORT: ${MONGODB_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - app_network
    volumes:
      - .:/app/
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
    ports:
      - ${PORT}:${PORT}

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env.aws
    environment:
      MONGODB_URI: ${MONGODB_URI}
    volumes:
      - data:/data/db
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    env_file:
      - .env.aws
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT=6379
      - REDIS_HOST=localhost
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    hostname: ${REDIS_HOST}
    networks:
      - app_network
    volumes:
      - cache:/data

volumes:
  data:
  cache:

networks:
  app_network:
    external: true
